# Generated by Django 3.1.7 on 2021-03-16 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please input project name', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(4, 'Project name should be at least 4 characters, ex. G965F')])),
                ('country', models.CharField(help_text='Please input country name', max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(2, 'Country name should be at least 2 characters')])),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
